package webdriverprograms;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.WebElement;
public class Vector_LoginAM {
public static void main(String args[]) throws Exception{
	WebDriver driver=new ChromeDriver();
	driver.navigate().to("https://www.vectorindia.org/student-login.html");
	Thread.sleep(3000);
	driver.findElement(By.name("j_username")).sendKeys("v21oe4p4");
	Thread.sleep(3000);
	driver.findElement(By.id("j_password")).sendKeys("Altaf@6804");
	Thread.sleep(3000);
	driver.findElement(By.xpath("/html/body/div[3]/section[2]/div/div[2]/div/div/form/div[3]/div/div/button/span")).click();
	Thread.sleep(3000);
	System.out.println("Login Successful");
	Actions ac=new Actions(driver);
	ac.moveToElement(driver.findElement(By.id("profile"))).perform();
	Thread.sleep(1000);
	driver.findElement(By.linkText("Home")).click();
	Thread.sleep(3000);
	System.out.println("Home Page Opened");
	driver.findElement(By.linkText("View Profile")).click();
	Thread.sleep(3000);
	System.out.println("Profile Viewed");
	ac.moveToElement(driver.findElement(By.id("test"))).perform();
	Thread.sleep(1000);
	driver.findElement(By.linkText("View Test Schedule")).click();
	Thread.sleep(3000);
	driver.findElement(By.linkText("View Test Marks")).click();
	Thread.sleep(3000);
	System.out.println("Viewed Test Marks");
	ac.moveToElement(driver.findElement(By.id("status"))).perform();
	driver.findElement(By.linkText("View Attendance")).click();
	Thread.sleep(1000);
	Select st1=new Select(driver.findElement(By.xpath("//*[@id=\"module\"]")));
	st1.selectByVisibleText("C");
	Thread.sleep(4000);
	st1.selectByVisibleText("Communication");
	Thread.sleep(4000);
	st1.selectByVisibleText("Aptitude");
	Thread.sleep(4000);
	st1.selectByVisibleText("8051");
	Thread.sleep(4000);
	st1.selectByVisibleText("C++");
	Thread.sleep(4000);
	st1.selectByVisibleText("Unix");
    Thread.sleep(4000);
    st1.selectByVisibleText("TCPIP");
    Thread.sleep(4000);
    st1.selectByVisibleText("ARM");
    Thread.sleep(4000);
    st1.selectByVisibleText("RTOS");
    Thread.sleep(4000);
    System.out.println("All Modules Attendence are Viewed");
	driver.findElement(By.linkText("View Assessment Status")).click();
	Thread.sleep(3000);
	System.out.println("Assessment status opened");
	driver.findElement(By.linkText("SMS History")).click();
	Thread.sleep(3000);
	ac.moveToElement(driver.findElement(By.id("placement"))).perform();
	Thread.sleep(1000);
	driver.findElement(By.linkText("Placement Profile")).click();
	Thread.sleep(3000);
	driver.findElement(By.linkText("Campus Confirmations")).click();
	Thread.sleep(3000);
	driver.findElement(By.linkText("Campus Information")).click();
	Thread.sleep(3000);
	System.out.println("Campus information Opened");
	driver.findElement(By.linkText("Upload Resume")).click();
	Thread.sleep(2000);
	/*WebElement fileInput= driver.findElement(By.xpath("//input[@type='file'][@value='Browse'][@name='namelist']"));
	Thread.sleep(3000);
	fileInput.sendKeys("C:/autovect/PATHAN%20ALTAF%20HUSSAIN_CV.pdf");
	Thread.sleep(6000);*/
	ac.moveToElement(driver.findElement(By.id("support"))).perform();
	Thread.sleep(1000);
	driver.findElement(By.linkText("Contact Support")).click();
	Thread.sleep(2000);
	Select st=new Select(driver.findElement(By.xpath("//*[@id=\"module\"]")));
	st.selectByVisibleText("leave");
	Thread.sleep(2000);
	driver.findElement(By.id("supmsg")).sendKeys("hello sir,i'm altaf hussain v21oe4p4 batch,i need leave for 5 days");
	Thread.sleep(2000);
	driver.findElement(By.linkText("Vectorians Group")).click();
    Thread.sleep(3000);
    driver.findElement(By.xpath("/html/body/div[1]/div[1]/table/tbody/tr/td[2]/a")).click();
    Thread.sleep(3000);
    driver.findElement(By.name("opassword")).sendKeys("Altaf@680");
    Thread.sleep(2000);
    driver.findElement(By.name("upassword")).sendKeys("Altaf@474");
    Thread.sleep(2000);
    driver.findElement(By.name("ucpassword")).sendKeys("Altaf@474");
    Thread.sleep(3000);
    driver.findElement(By.linkText("logout")).click();
	Thread.sleep(3000);
	System.out.println("Logout Successful");
	driver.close();
	System.out.println("Application Closed");
}
}
